alias stt_start='sudo systemctl start stt-api.service'
alias stt_status='sudo systemctl status stt-api.service'
alias stt_stop='sudo systemctl stop stt-api.service'
echo 'export JAVA_HOME=~/local/jdk-17' >> ~/.bashrc
echo 'export PATH=$JAVA_HOME/bin:$PATH' >> ~/.bashrc
export JAVA_HOME=/sw/qubientai/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
export JAVA_HOME=~/local/jdk-17
export PATH=$JAVA_HOME/bin:$PATH
